apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "solr.fullname" . }}
  labels:
    app: {{ template "solr.name" . }}
    chart: {{ template "solr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "solr.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "solr.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "solr.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: solr
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash"]
        args: ["-c", "solr start -f -c -h $(hostname).{{ template "solr.fullname" . }}-headless"]
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: ZK_HOST
          value: "{{ .Values.solr.zkHost }}"
        - name: SOLR_HOME
          value: /data
        - name: SOLR_PORT
          value: "8983"
        - name: SOLR_HEAP
          value: "{{ .Values.solr.memory }}"
        - name: ENABLE_REMOTE_JMX_OPTS
          value: "true"
        - name: RMI_PORT
          value: "18983"
        - name: GC_TUNE
          value: "-XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:CMSFullGCsBeforeCompaction=1 -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSTriggerPermRatio=80 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+UseLargePages -XX:+AggressiveOpts"
        ports:
        - containerPort: 8983
        - containerPort: 18983
        volumeMounts:
        - mountPath: /data
          name: datadir
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 12 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - {{ template "solr.name" . }}
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.volume.storage }}
      storageClassName: {{ .Values.volume.className }}
