apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "musicbrainz.fullname" . }}-postgres
  labels:
    app: {{ template "musicbrainz.name" . }}
    chart: {{ template "musicbrainz.chart" . }}
    component: postgres
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "musicbrainz.name" . }}
      component: postgres
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "musicbrainz.name" . }}
        component: postgres
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_USER
            value: musicbrainz
          - name: POSTGRES_PASSWORD
            value: musicbrainz
          - name: POD_IP
            valueFrom: { fieldRef: { fieldPath: status.podIP } }
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-vol
          resources:
{{ toYaml .Values.postgres.resources | indent 12 }}
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: {{ template "musicbrainz.fullname" . }}-postgres
    {{- with .Values.postgres.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.postgres.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.postgres.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
