apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "musicbrainz.fullname" . }}-postgres
  labels:
    app: {{ template "musicbrainz.name" . }}
    chart: {{ template "musicbrainz.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- if (eq "-" .Values.postgres.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "musicbrainz.fullname" . }}-import
  labels:
    app: {{ template "musicbrainz.name" . }}
    chart: {{ template "musicbrainz.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.import.persistence.size }}
{{- if (eq "-" .Values.import.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.import.persistence.storageClass }}
{{- end }}
