apiVersion: v1
kind: Service
metadata:
  name: {{ template "musicbrainz.fullname" . }}-postgres
  labels:
    app: {{ template "musicbrainz.name" . }}
    chart: {{ template "musicbrainz.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: {{ template "musicbrainz.name" . }}
    component: postgres
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
