# Default values for musicbrainz.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgres:
  image:
    repository: quay.io/hugoatease/musicbrainz-postgres
    tag: latest
    pullPolicy: IfNotPresent

  persistence:
    size: "60G"
    storageClass: "-"

  service:
    type: ClusterIP
    port: 5432

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

import:
  image:
    repository: quay.io/hugoatease/musicbrainz
    tag: latest
    pullPolicy: IfNotPresent

  persistence:
    size: "30G"
    storageClass: "-"

  config:
    redisHost: "redis"
    replicationToken: ""

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

replication:
  image:
    repository: quay.io/hugoatease/musicbrainz
    tag: latest
    pullPolicy: IfNotPresent

  config:
    redisHost: "redis"
    replicationToken: ""

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
