# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  sha256: c4fe834b33a12315c4df18129401e459e2392dc0952b876fbfcb2f987c2a7a7f

pitcher:
  dbhost: musicbrainz-postgres
  tracing: true

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    memory: 100Mi
    cpu: 50m
  limits:
    memory: 100Mi
    cpu: 50m
