# Default values for solr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/hugoatease/pitcher-solr
  tag: latest
  pullPolicy: IfNotPresent

solr:
  memory: 1024m
  zkHost: zookeeper-zookeeper:2181

service:
  type: ClusterIP
  port: 8983

volume:
  storage: 15Gi
  className:

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 1024Mi

nodeSelector: {}
